apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: nexodus-grafana
  namespace: observability
spec:
  ingress:
    enabled: true
    hostname: "grafana.127.0.0.1.nip.io"
    path: /
    pathType: Prefix
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "admin"
      admin_password: "floofykittens"
    auth:
      disable_login_form: false
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}
