apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: apiserver
          image: quay.io/nexodus/apiserver:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NEXAPI_LISTEN
              value: 0.0.0.0:8080
            - name: NEXAPI_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_DEBUG
            - name: NEXAPI_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: pgbouncer-host
            - name: NEXAPI_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: pgbouncer-port
            - name: NEXAPI_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: dbname
            - name: NEXAPI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: user
            - name: NEXAPI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: password
            - name: NEXAPI_DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_DB_SSLMODE
            - name: NEXAPI_IPAM_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_IPAM_URL
            - name: NEXAPI_OIDC_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_OIDC_URL
            - name: NEXAPI_OIDC_BACKCHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_OIDC_BACKCHANNEL
            - name: NEXAPI_INSECURE_TLS
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_INSECURE_TLS
            - name: NEXAPI_OIDC_CLIENT_ID_WEB
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: web-client-id
                  optional: false
            - name: NEXAPI_OIDC_CLIENT_SECRET_WEB
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: web-client-secret
                  optional: false
            - name: NEXAPI_OIDC_CLIENT_ID_CLI
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: cli-client-id
                  optional: false
            - name: NEXAPI_TRACE_ENDPOINT_OTLP
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_TRACE_ENDPOINT_OTLP
            - name: NEXAPI_TRACE_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_TRACE_INSECURE
            - name: NEXAPI_FFLAG_SECURITY_GROUPS
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_FFLAG_SECURITY_GROUPS
            - name: NEXAPI_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_REDIRECT_URL
            - name: NEXAPI_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_ORIGINS
            - name: NEXAPI_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_DOMAIN
            - name: NEXAPI_SCOPES
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_SCOPES
            - name: NEXAPI_REDIS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_REDIS_SERVER
            - name: NEXAPI_REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_REDIS_DB
            - name: NEXAPI_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_ENVIRONMENT
            - name: NEXAPI_FETCH_MGR
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_FETCH_MGR
            - name: NEXAPI_FETCH_MGR_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_FETCH_MGR_TIMEOUT
            - name: NEXAPI_DEVICE_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_DEVICE_CACHE_SIZE
            - name: NEXAPI_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: NEXAPI_URL
            - name: NEXAPI_TLS_KEY
              valueFrom:
                secretKeyRef:
                  name: nexodus-api-cert
                  key: tls.key

          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
              name: web
            - containerPort: 5080
              name: ext-authz
      restartPolicy: Always
