apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: apiserver
    literals:
      - NEXAPI_DEBUG=1
      - NEXAPI_IPAM_URL=http://ipam:9090
      - NEXAPI_OIDC_URL=https://auth.try.nexodus.127.0.0.1.nip.io/realms/nexodus
      - NEXAPI_OIDC_BACKCHANNEL=https://auth:8443/realms/nexodus
      - NEXAPI_INSECURE_TLS=1
      - NEXAPI_TRACE_ENDPOINT_OTLP="tempo.nexodus-monitoring.svc:4317"
      - NEXAPI_TRACE_INSECURE="1"
      - NEXAPI_FFLAG_SECURITY_GROUPS=false
      - NEXAPI_DB_SSLMODE=require
      - NEXAPI_DOMAIN=api.try.nexodus.127.0.0.1.nip.io
      - NEXAPI_URL=https://api.try.nexodus.127.0.0.1.nip.io
      - NEXAPI_REDIRECT_URL=https://try.nexodus.127.0.0.1.nip.io/#/login
      - NEXAPI_ORIGINS=https://try.nexodus.127.0.0.1.nip.io
      - NEXAPI_SCOPES=read:organizations,write:organizations,read:users,write:users,read:devices,write:devices
      - NEXAPI_REDIS_SERVER=redis:6379
      - NEXAPI_REDIS_DB=1
      - NEXAPI_ENVIRONMENT=development
      - NEXAPI_FETCH_MGR=redis
      - NEXAPI_FETCH_MGR_TIMEOUT=2s
      - NEXAPI_DEVICE_CACHE_SIZE=500
resources:
  - service.yaml
  - deployment.yaml
  - cronjob.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: apiserver
      app.kubernetes.io/instance: apiserver
      app.kubernetes.io/name: apiserver
