apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cli
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: backend-cli
          image: quay.io/go-oidc-agent/go-oidc-agent:49a615afe56d5bf4d1e7e381fb6d553337e4a014
          imagePullPolicy: IfNotPresent
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: backend-cli
                  key: DEBUG
            - name: OIDC_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: backend-cli
                  key: OIDC_PROVIDER
            - name: OIDC_BACKCHANNEL
              valueFrom:
                configMapKeyRef:
                  name: backend-cli
                  key: OIDC_BACKCHANNEL
            - name: INSECURE_TLS
              valueFrom:
                configMapKeyRef:
                  name: backend-cli
                  key: INSECURE_TLS
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: cli-client-id
                  optional: false
            - name: OIDC_FLOW
              valueFrom:
                configMapKeyRef:
                  name: backend-cli
                  key: OIDC_FLOW
            - name: BACKEND
              valueFrom:
                configMapKeyRef:
                  name: backend-cli
                  key: BACKEND
            - name: SCOPES
              valueFrom:
                configMapKeyRef:
                  name: backend-cli
                  key: SCOPES
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
