# Only [allowlist] is picked up by the LeakTK scanning service
[allowlist]
  description = "Repo Allowlist"
  paths = [
    # Some test ignores for working with the scanner's unit tests
    '''ignore\.d''',
    '''\.ignore\.txt$''',
    '''hack''',
    '''integration-tests''',

    # Ignore the .gitleaks.toml
    '''\.gitleaks\.toml$''',
  ]
  regexes = [
    # '''custom-regexes-to-ignore-here''',
  ]
