version: "3.7"

services:
  controller-db:
    image: docker.io/library/postgres
    environment:
      - POSTGRES_USER=${CONTROLLER_DB_USER}
      - POSTGRES_PASSWORD=${CONTROLLER_DB_PASSWORD}

  ipam-db:
    image: docker.io/library/postgres
    environment:
      - POSTGRES_USER=${IPAM_DB_USER}
      - POSTGRES_PASSWORD=${IPAM_DB_PASSWORD}

  ipam:
    image: ghcr.io/metal-stack/go-ipam
    depends_on:
      - ipam-db
    deploy:
      restart_policy:
        condition: on-failure
    command:
    - --grpc-server-endpoint=0.0.0.0:9090
    - postgres
    - --host=${IPAM_DB_HOST}
    - --dbname=ipam
    - --user=${IPAM_DB_USER}
    - --password=${IPAM_DB_PASSWORD}
  
  controller:
    image: quay.io/apex/controller:latest
    depends_on:
      - controller-db
      - ipam
      - keycloak
    build:
      context: .
      dockerfile: ./Containerfile.controller
    command:
      - "--keycloak-address=keycloak"
      - "--db-address=${CONTROLLER_DB_HOST}"
      - "--db-password=${CONTROLLER_DB_PASSWORD}"
      - "--ipam-address=${IPAM_ADDRESS}"
    environment:
      APEX_CONTROLLER_LOGLEVEL: debug

  ui:
    image: quay.io/apex/controller-ui:latest
    depends_on:
     - controller
     - keycloak
    build:
      context: .
      dockerfile: ./Containerfile.ui
      args:
        - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
        - VITE_KEYCLOAK_REALM=${VITE_KEYCLOAK_REALM}
        - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
        - VITE_CONTROLLER_URL=${VITE_CONTROLLER_URL}

  keycloak-db:
    image: docker.io/library/postgres
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}

  keycloak:
    image: quay.io/apex/keycloak:latest
    build:
      context: .
      dockerfile: ./Containerfile.keycloak
    depends_on:
      - keycloak-db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://${KEYCLOAK_DB_HOST}/keycloak
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - UI_URL=${UI_URL}
      - KC_PROXY=passthrough
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    command:
        - start
        - --optimized
        - --import-realm

  proxy:
    depends_on:
     - controller
     - keycloak
     - ui
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ./Containerfile.nginx
