apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: dex-secrets
    literals:
      - web-client-id=apex-web
      - web-client-secret=dhEN2dsqyUg5qmaDAdqi4CmH
      - cli-client-id=apex-cli
configMapGenerator:
  - name: dex
    files:
      - files/config.yaml
resources:
  - cert.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/component: dex
  app.kubernetes.io/instance: dex
  app.kubernetes.io/name: dex
