apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - issuer.yaml
namespace: apex-qa
patchesJson6902:
  - patch: |-
      - op: replace
        path: /data/APEX_OIDC_URL
        value: https://auth.qa.apex-hosted.cloud
    target:
      kind: ConfigMap
      name: apiserver
  - patch: |-
      - op: replace
        path: /data/DOMAIN
        value: https://api.qa.apex-hosted.cloud
      - op: replace
        path: /data/OIDC_PROVIDER
        value: https://auth.qa.apex-hosted.cloud
      - op: replace
        path: /data/ORIGINS
        value: https://qa.apex-hosted.cloud
      - op: replace
        path: /data/REDIRECT_URL
        value: https://qa.apex-hosted.cloud/#/login
    target:
      kind: ConfigMap
      name: backend-web
  - patch: |-
      - op: replace
        path: /data/DOMAIN
        value: https://api.qa.apex-hosted.cloud
      - op: replace
        path: /data/OIDC_PROVIDER
        value: https://auth.qa.apex-hosted.cloud
    target:
      kind: ConfigMap
      name: backend-cli
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.qa.apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.qa.apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: auth.qa.apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: auth.qa.apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: dex
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: qa.apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: qa.apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: frontend
images:
  - name: quay.io/apex/apiserver
    newTag: f8e367d9d1d42eca64d111e301a2f90f1893176c
  - name: quay.io/apex/frontend
    newTag: f8e367d9d1d42eca64d111e301a2f90f1893176c
