apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../released
  - issuer.yaml
  - sealed-secret.yaml
  - serviceaccount.yaml
components:
  - ../../components/promtail
  - ../../components/limitador
namespace: nexodus-qa
configMapGenerator:
  - behavior: replace
    literals:
      - hostname=auth.qa.nexodus.io
      - frontend-url=https://qa.nexodus.io
    name: auth-config
  - behavior: replace
    files:
      - files/nexodus.json
    name: realm
  - behavior: create
    files:
      - files/limits.yaml
    name: limitador-config
  - behavior: replace
    files:
      - files/envoy.yaml
    name: apiproxy-envoy-config
  - behavior: create
    files:
      - files/promtail.yaml
    name: promtail-config
  - behavior: merge
    literals:
      - APIPROXY_OIDC_URL=https://auth.qa.nexodus.io/realms/nexodus
      - APIPROXY_API_DOMAIN=api.qa.nexodus.io
      - APIPROXY_WEB_DOMAIN=qa.nexodus.io
      - APIPROXY_WEB_ORIGINS=https://qa.nexodus.io
      - ENVOY_COMP_LOG_LEVEL=upstream:info,http:debug,router:debug,jwt:debug
    name: apiproxy
  - behavior: merge
    literals:
      - NEXAPI_OIDC_URL=https://auth.qa.nexodus.io/realms/nexodus
      - NEXAPI_DOMAIN=api.qa.nexodus.io
      - NEXAPI_REDIRECT_URL=https://qa.nexodus.io/#/login
      - NEXAPI_ORIGINS=https://qa.nexodus.io
      - NEXAPI_ENVIRONMENT=qa
      - NEXAPI_DEBUG=0
    name: apiserver
patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: auth.qa.nexodus.io
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt
    target:
      kind: Certificate
      name: nexodus-auth-cert
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.qa.nexodus.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.qa.nexodus.io
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
      - op: remove
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-passthrough
      - op: replace
        path: /spec/rules/0/host
        value: auth.qa.nexodus.io
      - op: replace
        path: /spec/rules/0/http/paths/0/pathType
        value: ImplementationSpecific
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: ''
    target:
      kind: Ingress
      name: auth
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: qa.nexodus.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: qa.nexodus.io
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: frontend
  - patch: |-
      - op: add
        path: /rules/1
        value: {"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"resourceNames":["privileged"],"verbs":["use"]}
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: promtail-role
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 500Mi
    target:
      kind: StatefulSet
      name: redis
  - patch: |-
      - op: replace
        path: /spec/instances/0/replicas
        value: 1
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 6Gi
      - op: replace
        path: /spec/instances/0/resources/limits/cpu
        value: 2000m
      - op: replace
        path: /spec/instances/0/resources/limits/memory
        value: 2Gi
      - op: replace
        path: /spec/proxy/pgBouncer/replicas
        value: 1
      - op: replace
        path: /spec/proxy/pgBouncer/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/proxy/pgBouncer/resources/limits/memory
        value: 500Mi
      - op: replace
        path: /spec/proxy/pgBouncer/config/databases/ipam
        value: "host=database-primary port=5432 pool_size=15 reserve_pool=5 max_db_connections=20"
      - op: replace
        path: /spec/proxy/pgBouncer/config/databases/apiserver
        value: "host=database-primary port=5432 pool_size=35 reserve_pool=5 max_db_connections=40"
      - op: replace
        path: /spec/proxy/pgBouncer/config/databases/keycloak
        value: "host=database-primary port=5432 pool_size=35 reserve_pool=5 max_db_connections=40"
      - op: replace
        path: /spec/proxy/pgBouncer/config/global/max_client_conn
        value: "4000"
      - op: replace
        path: /spec/patroni/dynamicConfiguration/postgresql/parameters/max_connections
        value: "200"
      - op: replace
        path: /spec/patroni/dynamicConfiguration/postgresql/parameters/shared_buffers
        value: 256MB
    target:
      kind: PostgresCluster
      name: database
  - patch: |-
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: nexodus-serviceaccount
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: apiproxy
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 2000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2000Mi
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: apiserver
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1000Mi
    target:
      kind: Deployment
      name: auth
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 400Mi
    target:
      kind: Deployment
      name: frontend
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 300m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 500Mi
    target:
      kind: Deployment
      name: ipam
