apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: nexodus-grafana
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    auth.anonymous:
      enabled: true
    auth:
      disable_login_form: false
      disable_signout_menu: true
    auth.basic:
      enabled: true
    auth.proxy:
      enabled: true
      enable_login_token: true
      header_property: username
      header_name: X-Forwarded-User
    server:
      root_url: https://nexodus-grafana.apps.open-svc-sts.k1wl.p1.openshiftapps.com
  containers:
    - args:
        - '-provider=openshift'
        - '-pass-basic-auth=false'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:3000'
        - '-openshift-sar={"namespace":"nexodus","resource":"pods","verb":"get"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-openshift-service-account=grafana-serviceaccount'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-openshift-ca=/etc/grafana-configmaps/ocp-injected-certs/ca-bundle.crt'
        - '-skip-auth-regex=^/metrics'
      image: 'quay.io/openshift/origin-oauth-proxy'
      name: grafana-proxy
      ports:
        - containerPort: 9091
          name: https
      resources: {}
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-grafana-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: secret-grafana-proxy
          readOnly: false
  secrets:
    - grafana-tls
    - grafana-proxy
  configMaps:
    - ocp-injected-certs
  service:
    ports:
      - name: https
        port: 9091
        protocol: TCP
        targetPort: https
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: grafana-tls
  client:
    preferService: true
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-access"}}'
