apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: ipam
          image: quay.io/apex/go-ipam:v1.11.3
          imagePullPolicy: IfNotPresent
          env:
            - name: GOIPAM_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: database-pguser-ipam
                  key: host
            - name: GOIPAM_PG_PORT
              valueFrom:
                secretKeyRef:
                  name: database-pguser-ipam
                  key: port
            - name: GOIPAM_PG_USER
              valueFrom:
                secretKeyRef:
                  name: database-pguser-ipam
                  key: user
            - name: GOIPAM_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-pguser-ipam
                  key: password
            - name: GOIPAM_PG_DBNAME
              valueFrom:
                secretKeyRef:
                  name: database-pguser-ipam
                  key: dbname
            - name: GOIPAM_PG_SSLMODE
              value: require
          args:
            - --grpc-server-endpoint=0.0.0.0:9090
            - postgres
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=:9090"
                - "-service=api.v1.IpamService"
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=:9090"
                - "-service=api.v1.IpamService"
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
