apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: ipamdb
spec:
  image: quay.io/apex/crunchy-postgres:ubi8-14.6-0
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 2Gi
  backups:
    pgbackrest:
      image: quay.io/apex/crunchy-pgbackrest:ubi8-2.41-0
      global:
        # 7 Day Retention
        repo1-retention-full: "7"
        repo1-retention-full-type: time
      repoHost:
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 200m
      repos:
        - name: repo1
          schedules:
            # Sunday 4:42am
            full: "42 4 * * 0"
            # Monday-Sat 4:42am
            differential: "42 4 * * 1-6"
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
