# GCP Inventory
gcp_project: <GCP_PROJECT_NAME>
gcp_cred_kind: serviceaccount
gcp_cred_file: <GCP_CREDENTIAL_JSON_FILE>
zone: us-east4-c
region: us-east4
machine_type: e2-micro
node_count: 6
image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
ansible_user: nexodus
# View GCP VMs at: https://console.cloud.google.com/compute/instances
# View GCP VPC IP Addresses at: https://console.cloud.google.com/networking/addresses

### Controller Section (values are there for example, replace with your environment) ###
controller_address: <CONTROLLER_ADDRESS>
nexodus_binary: https://nexodus-io.s3.amazonaws.com/nexodus-amd64-linux
nexodus_zone_name: zone-hub
nexodus_org_prefix: 100.100.0.0/16

### Nexodus Auth ###
nexodus_auth_uid: kitteh1
nexodus_auth_password: floofykittens
nexodus_oidc_client_id_cli: nexodus-cli
nexodus_oidc_url: https://auth.try.nexodus.127.0.0.1.nip.io/realms/nexodus
nexodus_api_url: https://api.try.nexodus.127.0.0.1.nip.io
nexodus_url: https://try.nexodus.127.0.0.1.nip.io
