### Globals ###
ansible_user: nexodus                    # ssh username
inventory_location: inventory.txt     # leaving this as is will use the inventory.txt file in the base directory
ssh_pub_key: "<PUBLIC_SSH_KEY"
node_name: nexodus-azure-d1

### Controller Section (values are there for example, replace with your environment) ###
controller_address: <CONTROLLER_ADDRESS>
nexodus_binary: https://nexodus-io.s3.amazonaws.com/nexodus-amd64-linux
nexodus_zone_name: zone-hub
nexodus_org_prefix: 100.64.0.0/10

### Nexodus Auth ###
nexodus_auth_uid: kitteh1
nexodus_auth_password: floofykittens
nexodus_oidc_client_id_cli: nexodus-cli
nexodus_oidc_url: https://auth.try.nexodus.127.0.0.1.nip.io
nexodus_api_url: https://api.try.nexodus.127.0.0.1.nip.io
nexodus_url: https://try.nexodus.127.0.0.1.nip.io
