### Globals ###
ansible_user: apex                    # ssh username
inventory_location: inventory.txt     # leaving this as is will use the inventory.txt file in the base directory
ssh_pub_key: "<PUBLIC_SSH_KEY"
node_name: apex-azure-d1

### Controller Section (values are there for example, replace with your environment) ###
controller_address: <CONTROLLER_ADDRESS>
apex_binary: https://nexodus-io.s3.amazonaws.com/apex-amd64-linux
apex_zone_name: zone-hub
apex_zone_prefix: 10.185.0.0/20

### Apex Auth ###
apex_auth_uid: kitteh1
apex_auth_password: floofykittens
apex_oidc_client_id_cli: apex-cli
apex_oidc_url: https://auth.apex.local
apex_api_url: https://api.apex.local
apex_url: https://apex.local
