apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- issuer.yaml
namespace: apex
configMapGenerator:
- behavior: replace
  files:
  - files/config.yaml
  name: dex
patchesJson6902:
- patch: |-
    - op: replace
      path: /data/APEX_OIDC_URL
      value: https://auth.apex-hosted.cloud
  target:
    kind: ConfigMap
    name: apiserver
- patch: |-
    - op: replace
      path: /data/DOMAIN
      value: https://api.apex-hosted.cloud
    - op: replace
      path: /data/OIDC_PROVIDER
      value: https://auth.apex-hosted.cloud
    - op: replace
      path: /data/ORIGINS
      value: https://apex-hosted.cloud
    - op: replace
      path: /data/REDIRECT_URL
      value: https://auth.apex-hosted.cloud /#/login
  target:
    kind: ConfigMap
    name: backend-web
- patch: |-
    - op: replace
      path: /data/DOMAIN
      value: https://api.apex-hosted.cloud
    - op: replace
      path: /data/OIDC_PROVIDER
      value: https://auth.apex-hosted.cloud
  target:
    kind: ConfigMap
    name: backend-cli
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: api.apex-hosted.cloud
    - op: replace
      path: /spec/tls/0/hosts/0
      value: api.apex-hosted.cloud
  target:
    kind: Ingress
    name: apiproxy
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: auth.apex-hosted.cloud
    - op: replace
      path: /spec/tls/0/hosts/0
      value: auth.apex-hosted.cloud
  target:
    kind: Ingress
    name: dex
- patch: |-
    - op: replace
      path: /spec/dnsNames/0
      value: auth.apex-hosted.cloud
  target:
    kind: Certificate
    name: dex-cert
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: apex-hosted.cloud
    - op: replace
      path: /spec/tls/0/hosts/0
      value: apex-hosted.cloud
  target:
    kind: Ingress
    name: frontend
- patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1issuer
      value: letsencrypt
  target:
    kind: Ingress
    name: apiproxy
- patch: |-
    - op: remove
      path: /metadata/annotations/cert-manager.io~1issuer
    - op: remove
      path: /spec/tls
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-passthrough
      value: true
  target:
    kind: Ingress
    name: dex
- patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1issuer
      value: letsencrypt
  target:
    kind: Ingress
    name: frontend
- patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: letsencrypt
    - op: replace
      path: /spec/issuerRef/kind
      value: Issuer
  target:
    kind: Certificate
    name: dex-cert
images:
- name: quay.io/apex/apiserver
  newTag: 90268204644548af1eaa05eb4c4e3e55ef114b63
- name: quay.io/apex/frontend
  newTag: 90268204644548af1eaa05eb4c4e3e55ef114b63
