apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: backend-web
    literals:
      - DEBUG=1
      - OIDC_PROVIDER=https://auth.apex.local
      - DOMAIN=api.apex.local
      - REDIRECT_URL=https://apex.local/#/login
      - ORIGINS=https://apex.local
      - BACKEND=http://apiserver:8080
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/component: backend-web
  app.kubernetes.io/instance: backend-web
  app.kubernetes.io/name: backend-web
