apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - persistentvolumeclaim.yaml
  - service.yaml
  - statefulset.yaml
commonLabels:
  app.kubernetes.io/component: apiserver
  app.kubernetes.io/instance: apiserver
  app.kubernetes.io/name: apiserver
