apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: admin@nexodus.io
    privateKeySecretRef:
      name: letsencrypt-key
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
