# apiVersion: k8s.keycloak.org/v2alpha1
# kind: KeycloakRealmImport
# metadata:
#   name: nexodus-keycloak-realm
# spec:
#   keycloakCRName: auth
#   realm:
#     identityProviders:
#       - alias: github
#         internalId: b4d9c9be-2549-49cc-ab7f-39b512d615df
#         providerId: github
#         enabled: true
#         updateProfileFirstLoginMode: "on"
#         trustEmail: false
#         storeToken: false
#         addReadTokenRoleOnCreate: false
#         authenticateByDefault: false
#         linkOnly: false
#         firstBrokerLoginFlowAlias: first broker login
#         config:
#           clientSecret: "${GITHUB_CLIENT_SECRET}"
#           clientId: "${GITHUB_CLIENT_ID}"
#     identityProviderMappers: []
