apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: apiserver
          image: quay.io/apex/apiserver:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APEX_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_DEBUG
            - name: APEX_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: host
            - name: APEX_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: dbname
            - name: APEX_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: user
            - name: APEX_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: password
            - name: APEX_DB_SSLMODE
              value: require
            - name: APEX_IPAM_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_IPAM_URL
            - name: APEX_OIDC_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_OIDC_URL
            - name: APEX_OIDC_BACKCHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_OIDC_BACKCHANNEL
            - name: APEX_INSECURE_TLS
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_INSECURE_TLS
            - name: APEX_OIDC_CLIENT_ID_WEB
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: web-client-id
                  optional: false
            - name: APEX_OIDC_CLIENT_ID_CLI
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: cli-client-id
                  optional: false
            - name: APEX_TRACE_ENDPOINT_OTLP
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_TRACE_ENDPOINT_OTLP
            - name: APEX_TRACE_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_TRACE_INSECURE
            - name: APEX_FFLAG_MULTI_ORGANIZATION
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_FFLAG_MULTI_ORGANIZATION
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
