apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: apiserver
      app.kubernetes.io/instance: apiserver
      app.kubernetes.io/name: apiserver
  serviceName: "apiserver"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: apiserver
        app.kubernetes.io/instance: apiserver
        app.kubernetes.io/name: apiserver
    spec:
      containers:
        - name: apiserver-db
          image: docker.io/library/postgres:15.1-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              value: floofykittens
            - name: POSTGRES_USER
              value: apiserver
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql
              subPath: data
              name: postgresdb
        - name: apiserver
          image: quay.io/apex/apiserver:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APEX_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_DEBUG
            - name: APEX_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_DB_HOST
            - name: APEX_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_DB_NAME
            - name: APEX_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_DB_USER
            - name: APEX_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_DB_PASSWORD
            - name: APEX_IPAM_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_IPAM_URL
            - name: APEX_OIDC_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_OIDC_URL
            - name: APEX_OIDC_CLIENT_ID_WEB
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: web-client-id
                  optional: false
            - name: APEX_OIDC_CLIENT_ID_CLI
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: cli-client-id
                  optional: false
            - name: APEX_TRACE_ENDPOINT_OTLP
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_TRACE_ENDPOINT_OTLP
            - name: APEX_TRACE_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_TRACE_INSECURE
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: apiserver-postgres-pv-claim
