### Globals ###
aws_region: us-east-1                 # AWS region
aws_image_id: ami-052efd3df9dad4825   # Ubuntu 22.04 (this can be changed to most any Linux distro)
aws_key_name: patu-ci                 # the key pair on your aws account to use
aws_instance_type: t2.micro          # t2.micro is free tier eligable, but you can use any type to scale up, more examples [t2.large, t2.xlarge, t2.2xlarge]
aws_nodetype_tag: jaywalk-wireguard # Unique tag identifier for ec2 instances
ansible_user: ubuntu                  # this is the default user ID for your AMI image. Example, AWS AMI is ec2-user etc
security_group_description: "Wireguard Testing and CI for VPC perf-testing-vpc"
inventory_location: inventory.txt     # leaving this as is will use the inventory.txt file in the base directory
wireguard_port: 51871
wireguard_binary_bucket: https://perf-testing-submariner-s3.s3.amazonaws.com/jaywalk-amd64-linux
jaywalk_conf_file: endpoints.toml
peer_inventory: ./peer-inventory

### Blue VPC Details ###
secgroup_name_blue: JaywalkBlue           # the security group name can be an existing group or else it will be created by the playbook
node_count_blue: 2                         # the number of cluster nodes you want to deploy
vpc_id_blue: vpc-0566e09aa71f553c1         # VPC id from your aws account
aws_subnet_blue: subnet-0f8a1403fde2af94e  # VPC subnet id from your aws account

### Green VPC Details ###
secgroup_name_green: JaywalkGreen          # the security group name can be an existing group or else it will be created by the playbook
node_count_green: 2                         # the number of cluster nodes you want to deploy
vpc_id_green: vpc-27b7165a                  # VPC id from your aws account
aws_subnet_green: subnet-dabb9e97           # VPC subnet id from your aws account