apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: promtail-config
    files:
      - files/promtail.yaml
resources:
  - promtail-serviceaccount.yaml
  - promtail-role.yaml
  - promtail-rolebinding.yaml
  - promtail-daemonset.yaml
